{% set name = "ratelimit" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ratelimit-{{ version }}.tar.gz
  sha256: af8a9b64b821529aca09ebaf6d8d279100d766f19e90b5059ac6a718ca6dee42

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - ratelimit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomasbasham/ratelimit
  summary: API rate limit decorator
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ypriverol
